build site:
  image: harshitsngr/ubuntu-vue:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
unit test:
  image: harshitsngr/ubuntu-vue:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run build